language: python
install:
    - pip install -r requirements.txt
script:
    - pytest src/
after_success:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
notifications:
    email:
      - okv23200@gmail.com